import sharp from 'sharp';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { OrderView } from '@/types';

const escapeXml=(s:string)=>s.replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]||c));
const money=(n:number|null)=>n==null?'TBD':new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2}).format(n);

export function orderSummarySvg(order:OrderView){
 const rows=order.items.map((item,i)=>`<g transform="translate(72 ${510+i*92})"><text class="item" y="0">${escapeXml(item.member_name_snapshot?`${item.member_name_snapshot} · ${item.product_title_snapshot}`:item.product_title_snapshot)}</text><text class="meta" y="28">${escapeXml(item.barcode_snapshot)} · qty ${item.quantity}</text><text class="price" x="936" y="8" text-anchor="end">${escapeXml(money(item.price_snapshot))}</text></g>`).join('');
 const h=Math.max(1200,900+order.items.length*92);
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="${h}" viewBox="0 0 1080 ${h}"><defs><linearGradient id="bg" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#fffdfd"/><stop offset="1" stop-color="#fff1f6"/></linearGradient><style>.sans{font-family:Arial,sans-serif}.serif{font-family:Georgia,serif}.label{font:600 18px Arial;letter-spacing:4px;fill:#a67a89}.item{font:600 25px Arial;fill:#292126}.meta{font:17px Arial;fill:#8a7b82}.price{font:600 22px Arial;fill:#292126}</style></defs><rect width="1080" height="${h}" rx="48" fill="url(#bg)"/><circle cx="930" cy="130" r="112" fill="#f9d9e5" opacity=".55"/><circle cx="970" cy="95" r="46" fill="#e7e8eb" opacity=".75"/><text x="72" y="98" class="serif" font-size="60" fill="#c87998">pebi</text><text x="72" y="136" class="label">COLLECTIONS</text><text x="72" y="230" class="serif" font-size="64" fill="#241d21">Claim Summary</text><text x="72" y="274" class="sans" font-size="22" fill="#6f6268">from my collection, to yours.</text><line x1="72" y1="330" x2="1008" y2="330" stroke="#ead8df"/><text x="72" y="382" class="label">ORDER</text><text x="72" y="420" class="sans" font-size="28" font-weight="700" fill="#241d21">${escapeXml(order.order_number)}</text><text x="430" y="382" class="label">STATUS</text><text x="430" y="420" class="sans" font-size="24" fill="#241d21">${escapeXml(order.status.replaceAll('_',' '))}</text><text x="750" y="382" class="label">DATE</text><text x="750" y="420" class="sans" font-size="22" fill="#241d21">${escapeXml(new Date(order.created_at).toLocaleDateString('en-PH'))}</text><text x="72" y="466" class="meta">${escapeXml(order.email)} · ${escapeXml(order.preferred_contact_platform === 'instagram' ? (order.instagram_handle || '—') : (order.tiktok_handle || '—'))}</text>${rows}<line x1="72" y1="${520+order.items.length*92}" x2="1008" y2="${520+order.items.length*92}" stroke="#ead8df"/><text x="72" y="${585+order.items.length*92}" class="sans" font-size="20" fill="#6f6268">Items subtotal</text><text x="1008" y="${585+order.items.length*92}" text-anchor="end" class="sans" font-size="24" font-weight="700" fill="#241d21">${escapeXml(money(order.subtotal))}</text><text x="72" y="${627+order.items.length*92}" class="sans" font-size="20" fill="#6f6268">Shipping</text><text x="1008" y="${627+order.items.length*92}" text-anchor="end" class="sans" font-size="20" fill="#6f6268">calculated after confirmation</text><rect x="72" y="${690+order.items.length*92}" width="936" height="126" rx="24" fill="#fff" stroke="#ead8df"/><text x="104" y="${736+order.items.length*92}" class="label">PENDING CONFIRMATION</text><text x="104" y="${778+order.items.length*92}" class="sans" font-size="18" fill="#6f6268">Your items are not fully reserved until your claim has been confirmed by Pebicart.</text><text x="72" y="${h-80}" class="sans" font-size="16" fill="#9b8f94">This is a collection claim summary, not an official receipt or tax invoice.</text></svg>`;
}

export async function orderSummaryPng(order:OrderView){return sharp(Buffer.from(orderSummarySvg(order))).png().toBuffer();}
export async function orderSummaryPdf(order:OrderView){const pdfMoney=(n:number|null)=>n==null?'TBD':`PHP ${Number(n).toFixed(2)}`;const pdf=await PDFDocument.create();const page=pdf.addPage([595,842]);const serif=await pdf.embedFont(StandardFonts.TimesRoman);const sans=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);page.drawText('pebi',{x:42,y:785,size:32,font:serif,color:rgb(.78,.45,.58)});page.drawText('COLLECTIONS',{x:42,y:765,size:8,font:bold,color:rgb(.55,.45,.49)});page.drawText('Claim Summary',{x:42,y:710,size:30,font:serif,color:rgb(.15,.12,.14)});page.drawText(order.order_number,{x:42,y:670,size:13,font:bold});page.drawText(order.status.replaceAll('_',' '),{x:400,y:670,size:10,font:sans});page.drawText(`${order.email} | ${order.preferred_contact_platform === 'instagram' ? (order.instagram_handle || '-') : (order.tiktok_handle || '-')}`.slice(0,80),{x:42,y:646,size:8,font:sans,color:rgb(.45,.4,.42)});let y=610;for(const item of order.items){page.drawText(`${item.member_name_snapshot?`${item.member_name_snapshot} · `:''}${item.product_title_snapshot}`.slice(0,70),{x:42,y,size:11,font:bold});page.drawText(`${item.barcode_snapshot} · qty ${item.quantity}`,{x:42,y:y-17,size:8,font:sans,color:rgb(.45,.4,.42)});page.drawText(pdfMoney(item.price_snapshot),{x:455,y,size:9,font:bold});y-=52;}page.drawText(`Items subtotal: ${pdfMoney(order.subtotal)}`,{x:42,y:y-10,size:11,font:bold});page.drawText('Shipping: calculated after confirmation',{x:42,y:y-32,size:9,font:sans});page.drawText('PENDING CONFIRMATION',{x:42,y:y-80,size:9,font:bold,color:rgb(.67,.34,.47)});page.drawText('Your items are not fully reserved until your claim has been confirmed by Pebicart.',{x:42,y:y-100,size:8,font:sans});page.drawText('Collection claim summary — not an official receipt or tax invoice.',{x:42,y:30,size:7,font:sans,color:rgb(.5,.45,.47)});return Buffer.from(await pdf.save());}
