'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useBasket } from './BasketProvider';

export function ClaimForm(){
 const router=useRouter(); const {items,clear}=useBasket(); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const fd=new FormData(e.currentTarget);const payload={email:String(fd.get('email')||''),instagramHandle:String(fd.get('instagram')||''),tiktokHandle:String(fd.get('tiktok')||''),preferredContactPlatform:String(fd.get('preferred')||'instagram'),marketingOptIn:fd.get('marketing')==='on',notes:String(fd.get('notes')||''),items:items.map(i=>({product_id:i.product.id,quantity:i.quantity}))};
  const res=await fetch('/api/claims',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();setLoading(false);if(!res.ok){setError(data.error||'Could not submit claim.');return;}clear();router.push(`/order/${encodeURIComponent(data.order_number)}?token=${encodeURIComponent(data.public_token)}`);
 }
 if(!items.length)return <div className="empty-state large"><span>there’s nothing to claim yet.</span><p>Add your picks to the basket first.</p></div>;
 return <form className="claim-form" onSubmit={submit}><div className="form-intro"><div className="eyebrow">almost yours</div><h2>where should I find you?</h2><p>Your email is for claim confirmations and order updates. Marketing is always optional.</p></div><div className="field-grid"><label><span>Email *</span><input name="email" type="email" required placeholder="you@email.com"/></label><label><span>Preferred contact *</span><select name="preferred" defaultValue="instagram"><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select></label><label><span>Instagram handle</span><input name="instagram" placeholder="@pebicart"/></label><label><span>TikTok handle</span><input name="tiktok" placeholder="@pebicart"/></label></div><label><span>Anything I should know?</span><textarea name="notes" rows={4} placeholder="Optional claim or shipping note"/></label><label className="marketing-check"><input type="checkbox" name="marketing"/><span>Email me when Pebicart drops new collection items. <small>Optional. You can opt out later.</small></span></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="button button-primary button-block" disabled={loading}>{loading?'submitting claim...':'submit my claim'}</button><p className="microcopy">By submitting, you’re creating a claim request, not an official receipt or completed purchase. Items are pending until confirmed by Pebicart.</p></form>;
}
